config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail import urls as wagtail_urls

from allauth.account.views import confirm_email

from discuss_data.core.views import (
    landing_page,
    about_page,
    contacts_page,
    security_page,
    login_page,
)
from discuss_data.ddusers.views import datasets_act_feed
from discuss_data.dddatasets.views.core import category_page, category_list
from discuss_data.api.root import api

urlpatterns = [
    # remove next 4 lines and template files!
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #    "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL + "doc/", include("django.contrib.admindocs.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/", include(("discuss_data.ddusers.urls", "ddusers"), namespace="ddusers")
    ),
    # Your stuff: custom urls includes go here
    path("core/", include(("discuss_data.core.urls", "core"), namespace="core")),
    # hitcount
    path("hitcount/", include('hitcount.urls', namespace='hitcount')),
    # path(
    #    "publication/",
    #    include(
    #        ("discuss_data.ddpublications.urls", "ddpublications"),
    #        namespace="ddpublications",
    #    ),
    # ),
    path("dataset/", include("discuss_data.dddatasets.urls", namespace="dddatasets")),
    path("dhrep/", include("discuss_data.dhrep.urls", namespace="dhrep")),
    path('accounts/', include('allauth.urls')),
    # custom account confirmation email url, needs to come below accounts
    path('verify-email/<str:key>/',
        confirm_email,
        name="account_confirm_email"
    ),
    path("", landing_page, name="core.landing_page"),
    path("about/", about_page, name="core.about_page"),
    path("contacts/", contacts_page, name="core.contacts_page"),
    path("security/", security_page, name="core.security_page"),
    path("login/", login_page, name="core.login_page"),
    path("dashboard/", datasets_act_feed, name="ddusers.dashboard_page"),
    path("categories/", category_list, name="category_list"),
    path("categories/<slug:slug>/", category_page, name="category_page"),
    # API
    path("api/", api.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# wagtail URL def
urlpatterns += [
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("documentation/", include(wagtail_urls)),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

discuss_data/core/urls.py
from django.urls import path

from discuss_data.core import views

app_name = "core"

# public URLs
urlpatterns = [
    path("tags/keywords/", views.get_keyword_tags, name="tags"),
    path("polling/start/", views.polling_start, name="polling_start"),
    path("polling/stop/", views.polling_stop, name="polling_stop"),
    path("load/", views.load, name="load"),
    path("messages/", views.messages, name="messages"),
    path("search/", views.help_search, name="help_search"),
]

discuss_data/ddusers/urls.py
from django.urls import path

from discuss_data.ddusers import views


app_name = "ddusers"


urlpatterns = [
    # public URLs
    # path("search/", views.UsersListView.as_view(), name="search"), # this line breaks user search
    path("search/", views.search, name="search"),  # use this for searching
    path("verification/", views.verification_info, name="verification_info"),
    path("terms-of-use/", views.accept_tou, name="accept_tou"),
    path("first-steps/", views.first_steps, name="first_steps"),
    path("<uuid:us_uuid>/", views.UserDetailsView.as_view(), name="detail"),
    path("follow/<uuid:us_uuid>/", views.user_follow, name="follow"),
    path(
        "follow/datalist/<uuid:dl_uuid>/", views.datalist_follow, name="datalist_follow"
    ),
    path("follow/", views.user_follow_status, name="follow_status"),
    path("feed/users/", views.user_act_feed, name="user_feed"),
    path("feed/following/", views.following_act_feed, name="following_feed"),
    path("following/", views.following_users, name="following_users"),
    path("followers/", views.followers_users, name="followers_users"),
    path(
        "following/datasets/",
        views.list_following_datasets,
        name="list_following_datasets",
    ),
    path(
        "following/datalists/",
        views.list_following_datalists,
        name="list_following_datalists",
    ),
    path("followed/<str:follow_type>/", views.list_followed, name="list_followed"),
    # path("feed/notifications", views.notification_act_feed, name="notification_feed"),
    # path("follow/otherfeed/", views.other_feed, name="other_feed"),
    path("<uuid:us_uuid>/affiliations/", views.user_affiliations, name="affiliations",),
    path("<uuid:us_uuid>/datalists/", views.user_data_lists, name="data_lists",),
    path(
        "<uuid:us_uuid>/datalists/<uuid:dl_uuid>",
        views.user_get_data_list,
        name="get_data_list",
    ),
    path("<uuid:us_uuid>/projects/", views.user_projects, name="projects"),
    path("<uuid:us_uuid>/publications/", views.user_publications, name="publications",),
    path("<uuid:us_uuid>/datasets/", views.user_datasets, name="datasets"),
    path("<uuid:us_uuid>/lists/", views.user_lists_public, name="lists_public",),
    path("notifications/", views.user_notifications, name="notifications"),
    path("notifications/add/", views.user_notification, name="notification"),
    # edit urls
    # users search for dataset access control
    path("edit/search/", views.user_search, name="user_search"),
    # user profile: edit pages
    path("edit/", views.user_edit, name="edit"),
    path("edit/profile/", views.user_edit_profile, name="profile_edit"),
    # user profile: data lists
    path("follow/lists/add/dataset", views.dataset_to_list, name="dataset_to_list",),
    path("edit/lists/", views.user_edit_lists, name="edit_lists",),
    path("edit/lists/add/", views.user_edit_data_list, name="edit_list"),
    path("edit/lists/<uuid:dl_uuid>", views.user_edit_data_list, name="edit_list",),
    # user profile: affiliations
    path("edit/affiliations/", views.user_edit_affiliations, name="edit_affiliations",),
    path(
        "edit/affiliations/add/", views.user_edit_affiliation, name="edit_affiliation"
    ),
    path(
        "edit/affiliations/<uuid:af_uuid>/",
        views.user_edit_affiliation,
        name="edit_affiliation",
    ),
    # user profile: projects
    path("edit/projects/", views.user_edit_projects, name="edit_projects"),
    path("edit/projects/add/", views.user_edit_project, name="edit_project"),
    path("edit/projects/<uuid:pr_uuid>/", views.user_edit_project, name="edit_project"),
    # user profile: publications
    path("edit/publications/", views.user_edit_publications, name="edit_publications",),
    path(
        "edit/publications/add/", views.user_edit_publication, name="edit_publication"
    ),
    path(
        "edit/publications/<uuid:pub_uuid>/",
        views.user_edit_publication,
        name="edit_publication",
    ),
    # TODO: integrate ddpublications
    path("edit/countries/", views.user_countries, name="countries"),
    path("edit/tags/", views.user_tags, name="tags"),
    path("curation/", views.user_curation, name="curation"),
]

discuss_data/dhrep/urls.py
from django.urls import path

from discuss_data.dhrep import views

app_name = "dhrep"
urlpatterns = [
    path("token/<token>", views.show_token, name="show_token"),
    path("token/", views.get_token, name="get_token"),
]

discuss_data/dddatasets/views/core.py
import logging

from actstream import actions
from actstream.models import followers
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django_sendfile import sendfile
from django.views.generic.detail import DetailView, View
from hitcount.views import HitCountDetailView, HitCountMixin
from hitcount.models import HitCount

from guardian.shortcuts import get_perms

from discuss_data.core.decorators import dd_tou_accepted, dd_user_verified
from discuss_data.core.helpers import check_perms, is_curator_or_check_perms_for_ds
from discuss_data.core.views import core_search_view, get_search_params
from discuss_data.dddatasets.models import (
    Category,
    DataFile,
    DataSet,
    DataSetAccessRequest,
    DataSetManagementObject,
)
from discuss_data.dddatasets.utils import check_published

logger = logging.getLogger(__name__)


# ************
# public views
# ************


def search(request):
    return core_search_view(request, "dataset_index", 10)


# unused?
def listing(request):
    dsmos = DataSetManagementObject.objects.select_related("main_published_ds")
    datasets = list()
    for dsmo in dsmos:
        if dsmo.main_published_ds:
            datasets.append(dsmo.main_published_ds)

    return render(
        request,
        "dddatasets/listing.html",
        {"datasets": datasets, "pagetitle": _("Datasets")},
    )


def category_list(request):
    categories = Category.objects.all()
    return render(
        request,
        "dddatasets/category_list.html",
        {"categories": categories, "pagetitle": _("Categories")},
    )


def category_page(request, slug):
    logger.debug("category slug: {}".format(slug))
    category = get_object_or_404(Category, slug=slug)
    template = "dddatasets/search_results.html"
    datasets = category.get_published_datasets_category_all()
    search_params = get_search_params(request, None, category)
    # return core_search_view(request, "dataset_index", 10, category=category)
    return render(
        request,
        template,
        {
            "object_list": datasets,
            "search_params": search_params,
            "query": search_params["q"],
            "category": category,
        },
    )

class DataSetPublicHitCountView(HitCountDetailView):
    model = DataSet
    count_hit = True

    def get_object(self, **kwargs):
        return check_published(self.kwargs['uuid'])


class DataSetDetailView(DataSetPublicHitCountView):
    template_name = "dddatasets/detail.html"


class DataSetMetadataView(DataSetPublicHitCountView):
    template_name = "dddatasets/metadata.html"


class DataSetPublicationsView(DataSetPublicHitCountView):
    template_name = "dddatasets/publications.html"


class DataSetDiscussView(DataSetPublicHitCountView):
    template_name = "dddatasets/discuss.html"


class DataSetVersionsView(DataSetPublicHitCountView):
    template_name = "dddatasets/versions.html"


class DataSetFilesView(DataSetPublicHitCountView):
    template_name = "dddatasets/files.html"

    def get_datafiles(self, **kwargs):
        logger.debug("get datafiles")
        datafiles = list()
        ds = self.get_object(**kwargs)
        for datafile in ds.get_datafiles():
            try:
                filesize = datafile.file.size
            except FileNotFoundError:
                filesize = 10
            if datafile.data_file_type in (
                datafile.FILE_TYPE_DATA,
                datafile.FILE_TYPE_CONVERTED,
            ):
                # if dataset is RA check permissions
                if (
                    ds.data_access != ds.RESTRICTED_ACCESS
                    or is_curator_or_check_perms_for_ds(
                        "ra_view_dataset", self.request.user, datafile.dataset
                    )
                ):
                    datafiles.append(
                        (datafile, filesize, datafile.get_file_format(), datafile.hit_count.hits)
                    )
                else:
                    datafiles.append(("RA", filesize, datafile.get_file_format(), datafile.hit_count.hits))
            else:
                logger.debug(f"append {datafile}, type {type(datafile)}")
                datafiles.append((datafile, filesize, datafile.get_file_format(), datafile.hit_count.hits))
        return datafiles

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["datafiles"] = self.get_datafiles(**kwargs)
        return context


def files_pdf(request, uuid):
    ds = get_object_or_404(DataSet, uuid=uuid)
    try:
        pdf_file = DataFile.objects.filter(dataset=ds, data_file_type="PDF")[0]
    except DataFile.DoesNotExist as e:
        raise Http404 from e
    return download(request, pdf_file)


def files_zip(request, uuid):
    ds = get_object_or_404(DataSet, uuid=uuid)
    datafile = get_object_or_404(DataFile, dataset=ds, data_file_type="ZIP")

    if ds.data_access != ds.RESTRICTED_ACCESS or is_curator_or_check_perms_for_ds(
        "ra_view_dataset", request.user, datafile.dataset
    ):
        return download(request, datafile)
    return HttpResponseForbidden()


def files_download(request, uuid, df_uuid):
    logger.debug(f"File download")
    ds = get_object_or_404(DataSet, uuid=uuid)
    datafile = get_object_or_404(DataFile, uuid=df_uuid, dataset=ds)
    logger.info("datafile.file.path: %s", datafile.file.path, exc_info=1)
    logger.info(
        "datafile.get_download_file_name(): %s", datafile.get_download_file_name()
    )
    # check permissions for the dataset if it is of filetype DATA or CONVERTED
    if datafile.data_file_type in (
        datafile.FILE_TYPE_DATA,
        datafile.FILE_TYPE_CONVERTED,
    ):
        # if dataset is RA check permissions
        if (
            ds.data_access != ds.RESTRICTED_ACCESS
            or is_curator_or_check_perms_for_ds(
                "ra_view_dataset", request.user, datafile.dataset
            )
            or "view_dsmo"
            or "admin_dsmo"
            or "edit_dsmo" in get_perms(request.user, ds.dataset_management_object)
        ):
            return download(request, datafile)
        logger.debug(f"File download forbidden: {datafile}")
        return HttpResponseForbidden()
    return download(request, datafile)


def download(request, datafile):
    """sendfile download wrapper"""
    # count hit
    hit_count = HitCount.objects.get_for_object(datafile)
    hit_count_response = HitCountMixin.hit_count(request, hit_count)
    logger.debug(f"File download: {datafile}, {hit_count_response}")

    return sendfile(
        request,
        datafile.file.path,
        attachment=True,
        attachment_filename=datafile.get_download_file_name(),
    )








# ************
# views that require log-in
# ************
@login_required
@dd_tou_accepted
@dd_user_verified
def follow(request, uuid):
    # redirect if no intercooler request
    if not request.is_intercooler():
        return redirect("dddatasets:search")
    dataset = get_object_or_404(DataSet, uuid=uuid)

    if request.user in followers(dataset):
        actions.unfollow(request.user, dataset)
    else:
        actions.follow(request.user, dataset)
    return render(
        request,
        "ddusers/_follow_button.html",
        {
            "object": dataset,
            "follow_url": "dddatasets:follow",
            "follow_text": "Follow this Dataset",
        },
    )


@login_required
@dd_tou_accepted
@dd_user_verified
def access_request(request, uuid):
    ds = check_published(uuid)
    # check restricted access view permissions for the dataset
    if check_perms("ra_view_dataset", request.user, ds):
        # user has already access
        return HttpResponse(
            '<button class="btn btn-success" disabled>{}</button>'.format(
                _("You have access to this Dataset")
            )
        )

    if request.method == "POST":
        ds_access_request = DataSetAccessRequest(dataset=ds, user=request.user)
        ds_access_request.save()

        return HttpResponse(
            '<button class="btn btn-secondary" disabled>{}</button>'.format(
                ds_access_request
            )
        )
    else:
        ds_access_request = ds.get_access_request(request.user)
        if ds_access_request:
            return HttpResponse(
                '<button class="btn btn-secondary" disabled>{}</button>'.format(
                    ds_access_request
                )
            )
    return render(
        request,
        "dddatasets/_access_request.html",
        {
            "add_url": "dddatasets:access_request",
            "object": ds,
            "btn_text": "Request Access",
        },
    )

discuss_data/docupages/views.py
# Create your views here.

discuss_data/templates/dddatasets/prep/_archive_add.html
{% load static i18n crispy_forms_tags %}

{% if archive %}
    {% include "core/_edit_form.html" with form=form archivalsignature=archivalsignature icpostto="dddatasets:prep_edit_archivalsignature" icinclude="#archive-uuid" ictarget="#ds-content" formid="archivalsignature-form" %}
{% else %}
    {% include "core/_edit_form.html" with form=form archivalsignature=archivalsignature icinclude="#archive-uuid" formid="archivalsignature-form" %}
{% endif %}

{# Modal to add new #}
{% include "core/_add_modal.html" with objecttype="archive" objectname=archive add_url="dddatasets:prep_edit_archivalsignature" target="#add-archive-modal" ictarget="#add-archive-modal-target-span" form=archive_form %}

{% comment %} <div id="archival-signature-form" name="archive-search" ic-get-from="{% url 'dddatasets:prep_edit_archivalsignature_archive' ds.uuid %}" ic-trigger-on="load"></div> {% endcomment %}

discuss_data/templates/dddatasets/prep/_dataset_country_tags_list.html
{% load static %}

{% block content %}
<div id="ds-countries" >
        {% for tag in countries %}
        <input id="country-{{ tag.0.slug }}" type="hidden" name="country" value="{{ tag.0.slug }}" />
        <button class="btn btn-pill{% if tag.1 %} btn-primary{% else %} btn-outline-primary{% endif %} badge-tag" ic-post-to="{% url 'dddatasets:prep_country_tags_edit' ds.uuid %}" ic-include="#country-{{ tag.0.slug }}" ic-indicator="#country-{{ tag.0.slug }}-indicator" ic-target="#ds-countries" ic-on-beforeSend="xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');">
                {{ tag.0 }} <span id="country-{{ tag.0.slug }}-indicator" class="spinner-sm"></span>
        </button>
        {% endfor %}
</div>

{% if error_msg %}
        <p>{{ error_msg }}</p>
{% endif %}
{% endblock %}

discuss_data/templates/dddatasets/prep/_dataset_edit_datafile.html
{% load static crispy_forms_tags i18n core_tags %}



<form ic-post-to="{% url 'dddatasets:prep_edit_datafile' ds_uuid df_uuid %}"
    class="smallskip" enctype="multipart/form-data"
    id="ds-datafile-dropzone-{{ df_uuid }}">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8">
            <label>File* {% if ds_type == "DR" %} – {% trans "Note: Only a single PDF file can be uploaded per data review." %}{% endif %}</label>

            <div id="dropzone-{{ df_uuid }}" class="dropzone smallskip"></div>



            {% if form.instance.id %}<p>{% trans "Attached file" %}: {{ form.instance }}</p>{% endif %}

            <div class="progress smallskip">
                <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
            </div>
        </div>

        {% crispy form %}

{% comment %}         <div id='messages' ic-src="{% url 'core:messages' %}">
            {% include 'core/_messages.html' %}
        </div> {% endcomment %}

        <div class="col-md-12">
            <button class="btn btn-primary" type="submit" id="ds-datafile-upload-{{ df_uuid }}">Save {{ target }}<span class="spinner-sm"></span></button>

            {% if next_url %}
                <button class="btn btn-primary right" ic-get-from="{{ next_url }}" ic-push-url="true" ic-target="#ds-content">{% trans 'Back to Wizard' %}</button>
            {% endif %}
        </div>
    </div>
</form>


{# instantiate dropzone by triggering ic.complete event #}
<span class="ic-datafile-edit"
    data-url="{% url 'dddatasets:prep_edit_datafile' ds_uuid df_uuid %}" data-id="{{ df_uuid}}"
        data-message="{% trans 'Drop file here or click to open file browser' %}" ds-type="{{ ds_type }}"
    ic-get-from="{% url 'core:load' %}"
    ic-trigger-on="load">
</span>

discuss_data/templates/dddatasets/prep/_dataset_edit_publish_copyright.html
{% extends request.is_intercooler|yesno:"blank.html,dddatasets/_base_datasets_edit.html" %}
{% load static i18n core_tags wagtailcore_tags %}

{% block ic-content %}
<div id="ds-content">
    {% block dataset-nav %}
        {% include 'dddatasets/prep/_dataset_header.html' with ds=ds type='versions' %}
    {% endblock dataset-nav %}

    {% if manpage %}
        {% include 'dddatasets/_manual_page.html' with manpage=manpage %}
    {% endif %}

    <h1>{{ message }}</h1>

    {% with ds.get_dataset_type_display as ds_type %}
    <div class="card smallskip">
        <div class="card-header">
            <span class="pubcard-header">{% trans 'Submit' %} {{ ds.shorttitle }}, v{{ ds.version }}</span>
            <span class="float-sm-right">{% trans 'Step' %} 5 {% trans 'of' %} 6</span>
        </div>
        <div class="card-body">
            <h5 class="card-title">{% trans 'Data Submission Agreement, Copyright and Privacy Rights Declarations' %}</h5>
            {% if not ds.dsa %}
                <p class="card-text">{% trans 'Prior to publishing you need to generate a Data Submission Agreement' %}</p>

                <p><button class="btn btn-primary" ic-get-from="{% url 'dddatasets:prep_edit_versions' ds.uuid %}" ic-target="#ds-content" ic-push-url="true">{% trans 'Go to DSA' %}</button></p>
            {% else %}
            <p class="card-text">
                <p>{% trans 'Prior to publishing please acknowledge that your' %} {{ ds_type|lower }} {% trans 'and all provided additional documents do not infringe any copyrights of third parties and that no personal privacy rights or data protection regulations are violated.' %}</p>

                {% for block in copyright_declaration_page.body %}
                    {{ block }}
                {% endfor %}

                {% for block in privacy_rights_declaration_page.body %}
                    {{ block }}
                {% endfor %}

                {% include 'core/_edit_form.html' with ds=ds form=form sub_form=sub_form_copyright sub_form2=sub_form_privacy_rights user=request.user updated=updated err=err target=target ictarget="#ds-content" %}
            </p>
            {% endif %}

            {% if ds.copyright_declaration and ds.privacy_rights_declaration and ds.dsa.dsa_accepted %}
                <button class="btn btn-primary" ic-get-from="{% url 'dddatasets:prep_edit_publish_request' ds.uuid %}" ic-target="#ds-content">{% trans 'Final step: Submit' %}</button>
            {% else %}
                <button class="btn btn-primary" disabled>{% trans 'Final step: Submit Dataset' %}</button>
            {% endif %}
            <button class="btn btn-outline-primary" ic-get-from="{% url 'dddatasets:prep_edit_versions' ds.uuid %}" ic-target="#ds-content">{% trans "Cancel" %}</button>
        </div>
    </div>
    {% endwith %}


</div>
{% endblock %}

discuss_data/templates/dddatasets/prep/_dataset_edit_publish_final_upload.html
{% extends request.is_intercooler|yesno:"blank.html,dddatasets/_base_datasets_edit.html" %}
{% load static i18n core_tags %}

{% block ic-content %}
<div ic-src="{% url 'dddatasets:prep_edit_publish_final_upload' ds_uuid %}" ic-poll="3s">

{% for file, status_code in status.items %}
    <p>
        {% trans 'Uploading File with ID' %} {{ file }}...
        {% if not status_code %}
            {% comment %}
            <button class="badge badge-primary" type="button" disabled>
                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    {% trans "Upload in progress, please be patient" %}
            </button>
            {% endcomment %}
            <span class="badge badge-primary">
                {% trans "Upload in progress, please be patient" %}
                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            </span>
        {% else %}
            <span class="badge badge-secondary">{% trans 'Upload finished' %}</span>
        {% endif %}
    </p>
{% endfor %}

{% if upload_complete %}
    <span ic-get-from="{% url 'core:polling_stop' %}" ic-trigger-on="load"></span>
    <p>
        <div id="publish_status" ic-get-from="{% url 'dddatasets:prep_edit_publish_final_publish' ds_uuid %}" ic-trigger-from="#publish" ic-replace-target="this" ic-poll="1s">
            <span class="badge badge-primary">
                {% trans 'Initialize publication' %}...
                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            <span>
        </div>
    </p>
{% endif %}
</div>
{% endblock %}

discuss_data/templates/dddatasets/prep/_dataset_header.html
{% load static i18n %}

<div class="col-md-12 datasetheader">
    <h4>
        {% if ds.is_frozen %}<span class="badge badge-private">{% trans "frozen" %}</span> {% endif %} <span class="slim">{% trans "Preparation" %}</span> <span class="font-weight-bold">{{ ds.get_dataset_type_display }}</span>
    </h4>
    <h1><a href="{% url 'dddatasets:detail' ds.uuid %}">{{ ds.get_fulltitle }}, v{{ ds.version }}</a></h1>

    <div class="smallskip">
        {% include 'ddusers/_user-image.html' with user_uuid=ds.owner.uuid user_photo=ds.owner.photo height=30 %}
        <a href="{% url "ddusers:detail" ds.owner.uuid %}">{{ ds.owner.get_academic_name }}</a>
    </div>

    <span ic-src="{% url 'dddatasets:prep_refresh_header' ds.uuid %}" ic-deps="{% url 'dddatasets:prep_edit_detail' ds.uuid %}">
        {% include 'dddatasets/prep/_dataset_refresh_header.html' with ds=ds %}
    </span>
    <div class="smallskip">
        {% if ds.prev_owner_dataset.all.count > 0 %}{% trans "Dataset ownership has been transferred. Previous users: " %}{% for dspo in ds.prev_owner_dataset.all %}<a href="{% url "ddusers:detail" dspo.user.uuid %}">{{ dspo.user.get_academic_name }}</a> ({% trans "until" %} {{ dspo.until }}){% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}
    </div>

    {% include 'dddatasets/prep/_nav_datasets.html' with ds=ds type=type %}

</div>

discuss_data/templates/dddatasets/prep/_dataset_image.html
{% load static i18n %}

<div class="container">
    <label>Image</label>
    <div class="image-dataset-container">

        {% if ds.image %}
            <img src="{{ ds.image.url }}" alt="image related to dataset {{ ds.title }}" id="image-dataset" />
        {% else %}
            <img src={% static "images/ds-default.svg" %} alt="default image for dataset {{ ds.title }}" id="image-dataset" />
        {% endif %}
        <div id="image-dataset-overlay" data-toggle="modal" data-target="#dsImageModal">
            <span class="i-camera-xl"></span>
        </div>
    </div>
</div>

discuss_data/templates/dddatasets/prep/_dataset_publish_success.html
{% load static i18n core_tags %}

<h5 class="card-title">
    {% trans 'Dataset has been published successfully' %}
</h5>
<p class="card-text">
    {% include 'dddatasets/_dataset_citation.html' with ds=ds %}

    {% trans 'Congratulations! The publication of your dataset' %} {{ ds }} as {{ ds.data_access.label }} {% trans 'was successful!' %}
    <p>
        <a class="btn btn-primary" href="{% url 'dddatasets:detail' ds.uuid %}">{% trans 'View' %}</a>

        <button class="btn btn-outline-primary" ic-get-from="{% url 'dddatasets:prep_edit_versions' ds.uuid %}" ic-target="#ds-content">{% trans "Versions" %}</button>
    </p>
</p>