config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail import urls as wagtail_urls

from allauth.account.views import confirm_email

from discuss_data.core.views import (
    landing_page,
    about_page,
    contacts_page,
    security_page,
    login_page,
)
from discuss_data.ddusers.views import datasets_act_feed
from discuss_data.dddatasets.views.core import category_page, category_list
from discuss_data.api.root import api

urlpatterns = [
    # remove next 4 lines and template files!
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #    "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL + "doc/", include("django.contrib.admindocs.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/", include(("discuss_data.ddusers.urls", "ddusers"), namespace="ddusers")
    ),
    # Your stuff: custom urls includes go here
    path("core/", include(("discuss_data.core.urls", "core"), namespace="core")),
    # hitcount
    path("hitcount/", include('hitcount.urls', namespace='hitcount')),
    # path(
    #    "publication/",
    #    include(
    #        ("discuss_data.ddpublications.urls", "ddpublications"),
    #        namespace="ddpublications",
    #    ),
    # ),
    path("dataset/", include("discuss_data.dddatasets.urls", namespace="dddatasets")),
    path("dhrep/", include("discuss_data.dhrep.urls", namespace="dhrep")),
    path('accounts/', include('allauth.urls')),
    # custom account confirmation email url, needs to come below accounts
    path('verify-email/<str:key>/',
        confirm_email,
        name="account_confirm_email"
    ),
    path("", landing_page, name="core.landing_page"),
    path("about/", about_page, name="core.about_page"),
    path("contacts/", contacts_page, name="core.contacts_page"),
    path("security/", security_page, name="core.security_page"),
    path("login/", login_page, name="core.login_page"),
    path("dashboard/", datasets_act_feed, name="ddusers.dashboard_page"),
    path("categories/", category_list, name="category_list"),
    path("categories/<slug:slug>/", category_page, name="category_page"),
    # API
    path("api/", api.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# wagtail URL def
urlpatterns += [
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("documentation/", include(wagtail_urls)),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

discuss_data/core/urls.py
from django.urls import path

from discuss_data.core import views

app_name = "core"

# public URLs
urlpatterns = [
    path("tags/keywords/", views.get_keyword_tags, name="tags"),
    path("polling/start/", views.polling_start, name="polling_start"),
    path("polling/stop/", views.polling_stop, name="polling_stop"),
    path("load/", views.load, name="load"),
    path("messages/", views.messages, name="messages"),
    path("search/", views.help_search, name="help_search"),
]

discuss_data/ddusers/urls.py
from django.urls import path

from discuss_data.ddusers import views


app_name = "ddusers"


urlpatterns = [
    # public URLs
    # path("search/", views.UsersListView.as_view(), name="search"), # this line breaks user search
    path("search/", views.search, name="search"),  # use this for searching
    path("verification/", views.verification_info, name="verification_info"),
    path("terms-of-use/", views.accept_tou, name="accept_tou"),
    path("first-steps/", views.first_steps, name="first_steps"),
    path("<uuid:us_uuid>/", views.UserDetailsView.as_view(), name="detail"),
    path("follow/<uuid:us_uuid>/", views.user_follow, name="follow"),
    path(
        "follow/datalist/<uuid:dl_uuid>/", views.datalist_follow, name="datalist_follow"
    ),
    path("follow/", views.user_follow_status, name="follow_status"),
    path("feed/users/", views.user_act_feed, name="user_feed"),
    path("feed/following/", views.following_act_feed, name="following_feed"),
    path("following/", views.following_users, name="following_users"),
    path("followers/", views.followers_users, name="followers_users"),
    path(
        "following/datasets/",
        views.list_following_datasets,
        name="list_following_datasets",
    ),
    path(
        "following/datalists/",
        views.list_following_datalists,
        name="list_following_datalists",
    ),
    path("followed/<str:follow_type>/", views.list_followed, name="list_followed"),
    # path("feed/notifications", views.notification_act_feed, name="notification_feed"),
    # path("follow/otherfeed/", views.other_feed, name="other_feed"),
    path("<uuid:us_uuid>/affiliations/", views.user_affiliations, name="affiliations",),
    path("<uuid:us_uuid>/datalists/", views.user_data_lists, name="data_lists",),
    path(
        "<uuid:us_uuid>/datalists/<uuid:dl_uuid>",
        views.user_get_data_list,
        name="get_data_list",
    ),
    path("<uuid:us_uuid>/projects/", views.user_projects, name="projects"),
    path("<uuid:us_uuid>/publications/", views.user_publications, name="publications",),
    path("<uuid:us_uuid>/datasets/", views.user_datasets, name="datasets"),
    path("<uuid:us_uuid>/lists/", views.user_lists_public, name="lists_public",),
    path("notifications/", views.user_notifications, name="notifications"),
    path("notifications/add/", views.user_notification, name="notification"),
    # edit urls
    # users search for dataset access control
    path("edit/search/", views.user_search, name="user_search"),
    # user profile: edit pages
    path("edit/", views.user_edit, name="edit"),
    path("edit/profile/", views.user_edit_profile, name="profile_edit"),
    # user profile: data lists
    path("follow/lists/add/dataset", views.dataset_to_list, name="dataset_to_list",),
    path("edit/lists/", views.user_edit_lists, name="edit_lists",),
    path("edit/lists/add/", views.user_edit_data_list, name="edit_list"),
    path("edit/lists/<uuid:dl_uuid>", views.user_edit_data_list, name="edit_list",),
    # user profile: affiliations
    path("edit/affiliations/", views.user_edit_affiliations, name="edit_affiliations",),
    path(
        "edit/affiliations/add/", views.user_edit_affiliation, name="edit_affiliation"
    ),
    path(
        "edit/affiliations/<uuid:af_uuid>/",
        views.user_edit_affiliation,
        name="edit_affiliation",
    ),
    # user profile: projects
    path("edit/projects/", views.user_edit_projects, name="edit_projects"),
    path("edit/projects/add/", views.user_edit_project, name="edit_project"),
    path("edit/projects/<uuid:pr_uuid>/", views.user_edit_project, name="edit_project"),
    # user profile: publications
    path("edit/publications/", views.user_edit_publications, name="edit_publications",),
    path(
        "edit/publications/add/", views.user_edit_publication, name="edit_publication"
    ),
    path(
        "edit/publications/<uuid:pub_uuid>/",
        views.user_edit_publication,
        name="edit_publication",
    ),
    # TODO: integrate ddpublications
    path("edit/countries/", views.user_countries, name="countries"),
    path("edit/tags/", views.user_tags, name="tags"),
    path("curation/", views.user_curation, name="curation"),
]

discuss_data/dhrep/urls.py
from django.urls import path

from discuss_data.dhrep import views

app_name = "dhrep"
urlpatterns = [
    path("token/<token>", views.show_token, name="show_token"),
    path("token/", views.get_token, name="get_token"),
]

discuss_data/dddatasets/views/core.py
import logging

from actstream import actions
from actstream.models import followers
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django_sendfile import sendfile
from django.views.generic.detail import DetailView, View
from hitcount.views import HitCountDetailView, HitCountMixin
from hitcount.models import HitCount

from guardian.shortcuts import get_perms

from discuss_data.core.decorators import dd_tou_accepted, dd_user_verified
from discuss_data.core.helpers import check_perms, is_curator_or_check_perms_for_ds
from discuss_data.core.views import core_search_view, get_search_params
from discuss_data.dddatasets.models import (
    Category,
    DataFile,
    DataSet,
    DataSetAccessRequest,
    DataSetManagementObject,
)
from discuss_data.dddatasets.utils import check_published

logger = logging.getLogger(__name__)


# ************
# public views
# ************


def search(request):
    return core_search_view(request, "dataset_index", 10)


# unused?
def listing(request):
    dsmos = DataSetManagementObject.objects.select_related("main_published_ds")
    datasets = list()
    for dsmo in dsmos:
        if dsmo.main_published_ds:
            datasets.append(dsmo.main_published_ds)

    return render(
        request,
        "dddatasets/listing.html",
        {"datasets": datasets, "pagetitle": _("Datasets")},
    )


def category_list(request):
    categories = Category.objects.all()
    return render(
        request,
        "dddatasets/category_list.html",
        {"categories": categories, "pagetitle": _("Categories")},
    )


def category_page(request, slug):
    logger.debug("category slug: {}".format(slug))
    category = get_object_or_404(Category, slug=slug)
    template = "dddatasets/search_results.html"
    datasets = category.get_published_datasets_category_all()
    search_params = get_search_params(request, None, category)
    # return core_search_view(request, "dataset_index", 10, category=category)
    return render(
        request,
        template,
        {
            "object_list": datasets,
            "search_params": search_params,
            "query": search_params["q"],
            "category": category,
        },
    )

class DataSetPublicHitCountView(HitCountDetailView):
    model = DataSet
    count_hit = True

    def get_object(self, **kwargs):
        return check_published(self.kwargs['uuid'])


class DataSetDetailView(DataSetPublicHitCountView):
    template_name = "dddatasets/detail.html"


class DataSetMetadataView(DataSetPublicHitCountView):
    template_name = "dddatasets/metadata.html"


class DataSetPublicationsView(DataSetPublicHitCountView):
    template_name = "dddatasets/publications.html"


class DataSetDiscussView(DataSetPublicHitCountView):
    template_name = "dddatasets/discuss.html"


class DataSetVersionsView(DataSetPublicHitCountView):
    template_name = "dddatasets/versions.html"


class DataSetFilesView(DataSetPublicHitCountView):
    template_name = "dddatasets/files.html"

    def get_datafiles(self, **kwargs):
        logger.debug("get datafiles")
        datafiles = list()
        ds = self.get_object(**kwargs)
        for datafile in ds.get_datafiles():
            try:
                filesize = datafile.file.size
            except FileNotFoundError:
                filesize = 10
            if datafile.data_file_type in (
                datafile.FILE_TYPE_DATA,
                datafile.FILE_TYPE_CONVERTED,
            ):
                # if dataset is RA check permissions
                if (
                    ds.data_access != ds.RESTRICTED_ACCESS
                    or is_curator_or_check_perms_for_ds(
                        "ra_view_dataset", self.request.user, datafile.dataset
                    )
                ):
                    datafiles.append(
                        (datafile, filesize, datafile.get_file_format(), datafile.hit_count.hits)
                    )
                else:
                    datafiles.append(("RA", filesize, datafile.get_file_format(), datafile.hit_count.hits))
            else:
                logger.debug(f"append {datafile}, type {type(datafile)}")
                datafiles.append((datafile, filesize, datafile.get_file_format(), datafile.hit_count.hits))
        return datafiles

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["datafiles"] = self.get_datafiles(**kwargs)
        return context


def files_pdf(request, uuid):
    ds = get_object_or_404(DataSet, uuid=uuid)
    try:
        pdf_file = DataFile.objects.filter(dataset=ds, data_file_type="PDF")[0]
    except DataFile.DoesNotExist as e:
        raise Http404 from e
    return download(request, pdf_file)


def files_zip(request, uuid):
    ds = get_object_or_404(DataSet, uuid=uuid)
    datafile = get_object_or_404(DataFile, dataset=ds, data_file_type="ZIP")

    if ds.data_access != ds.RESTRICTED_ACCESS or is_curator_or_check_perms_for_ds(
        "ra_view_dataset", request.user, datafile.dataset
    ):
        return download(request, datafile)
    return HttpResponseForbidden()


def files_download(request, uuid, df_uuid):
    logger.debug(f"File download")
    ds = get_object_or_404(DataSet, uuid=uuid)
    datafile = get_object_or_404(DataFile, uuid=df_uuid, dataset=ds)
    logger.info("datafile.file.path: %s", datafile.file.path, exc_info=1)
    logger.info(
        "datafile.get_download_file_name(): %s", datafile.get_download_file_name()
    )
    # check permissions for the dataset if it is of filetype DATA or CONVERTED
    if datafile.data_file_type in (
        datafile.FILE_TYPE_DATA,
        datafile.FILE_TYPE_CONVERTED,
    ):
        # if dataset is RA check permissions
        if (
            ds.data_access != ds.RESTRICTED_ACCESS
            or is_curator_or_check_perms_for_ds(
                "ra_view_dataset", request.user, datafile.dataset
            )
            or "view_dsmo"
            or "admin_dsmo"
            or "edit_dsmo" in get_perms(request.user, ds.dataset_management_object)
        ):
            return download(request, datafile)
        logger.debug(f"File download forbidden: {datafile}")
        return HttpResponseForbidden()
    return download(request, datafile)


def download(request, datafile):
    """sendfile download wrapper"""
    # count hit
    hit_count = HitCount.objects.get_for_object(datafile)
    hit_count_response = HitCountMixin.hit_count(request, hit_count)
    logger.debug(f"File download: {datafile}, {hit_count_response}")

    return sendfile(
        request,
        datafile.file.path,
        attachment=True,
        attachment_filename=datafile.get_download_file_name(),
    )








# ************
# views that require log-in
# ************
@login_required
@dd_tou_accepted
@dd_user_verified
def follow(request, uuid):
    # redirect if no intercooler request
    if not request.is_intercooler():
        return redirect("dddatasets:search")
    dataset = get_object_or_404(DataSet, uuid=uuid)

    if request.user in followers(dataset):
        actions.unfollow(request.user, dataset)
    else:
        actions.follow(request.user, dataset)
    return render(
        request,
        "ddusers/_follow_button.html",
        {
            "object": dataset,
            "follow_url": "dddatasets:follow",
            "follow_text": "Follow this Dataset",
        },
    )


@login_required
@dd_tou_accepted
@dd_user_verified
def access_request(request, uuid):
    ds = check_published(uuid)
    # check restricted access view permissions for the dataset
    if check_perms("ra_view_dataset", request.user, ds):
        # user has already access
        return HttpResponse(
            '<button class="btn btn-success" disabled>{}</button>'.format(
                _("You have access to this Dataset")
            )
        )

    if request.method == "POST":
        ds_access_request = DataSetAccessRequest(dataset=ds, user=request.user)
        ds_access_request.save()

        return HttpResponse(
            '<button class="btn btn-secondary" disabled>{}</button>'.format(
                ds_access_request
            )
        )
    else:
        ds_access_request = ds.get_access_request(request.user)
        if ds_access_request:
            return HttpResponse(
                '<button class="btn btn-secondary" disabled>{}</button>'.format(
                    ds_access_request
                )
            )
    return render(
        request,
        "dddatasets/_access_request.html",
        {
            "add_url": "dddatasets:access_request",
            "object": ds,
            "btn_text": "Request Access",
        },
    )

discuss_data/docupages/views.py
# Create your views here.

discuss_data/templates/core/_add_modal.html
{% load static i18n crispy_forms_tags %}

<div class="modal" id="add-{{ objecttype}}-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{% trans "Adding" %} {{ objecttype }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" ic-get-from="{% url 'core:polling_start' %}" ic-target="#pollstatus"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                {% include "core/_edit_form.html" with form=form formid="add-archive-form" icpostto="dddatasets:prep_new_archive_add" ds=ds %}
            </div>
            <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal" ic-get-from="{% url 'core:polling_start' %}" ic-target="#pollstatus">{% trans "Cancel" %}<span class="glyphicon glyphicon-ban-circle"></span></button>
                <span id="add-archive-modal-target-span"></span>
            </div>
        </div>
    </div>
</div>

discuss_data/templates/core/_bool_button.html
{% load crispy_forms_field i18n core_tags %}

<label for="id_{{ field.html_name }}">
    {{ field }} {% trans "remove" %}
</label>

discuss_data/templates/core/_checkbox.html
{% load crispy_forms_field i18n core_tags %}

<div class="container">
    <div class="col-md-6 custom-control custom-checkbox smallskip">
        {{ field }}
        <label for="id_{{ field.html_name }}" class="custom-control-label">{% trans "Set as main affiliation" %}</label>
    </div>
</div>

discuss_data/templates/core/_confirm_modal.html
{% load static i18n %}

<div class="modal" id="confirmModal{{ objectid}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{% trans "Deleting" %} {{ objecttype }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div>{% trans "Please confirm the deletion of the" %} {{ objecttype }}:<br><i>{{ objectname }}</i>.</div>
            </div>
            <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal" ic-get-from="{% url 'core:polling_start' %}" ic-target="#pollstatus">{% trans "Cancel" %}<span class="glyphicon glyphicon-ban-circle"></span></button>
                    <form>
                        <input type="hidden" name="objectid" value="{{ objectid }}" />
                        <button class="btn btn-danger" data-dismiss="modal" ic-target="{{ ictarget }}" ic-delete-from="{% if dsid %}{% url delete_url dsid %}{% else %}{% url delete_url %}{% endif %}" ic-on-beforeSend="xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');removeModal();">
                            {% trans "Delete" %}
                        </button>
                    </form>


                <span id="confirmModal-target-span"></span>
            </div>
        </div>
    </div>
</div>

discuss_data/templates/core/_edit_form.html
{% load static crispy_forms_tags core_tags i18n %}

{% block content %}

{% if error_msg %}
<p>Errors: {{ error_msg }}</p>
{% endif %}

{% if form %}
    <form method="POST" {% if formid %}id={{ formid }}{% endif %} class=".sortable-ignore" ic-post-to="{% if icpostto %}{% url icpostto ds.uuid %}{% else %}{{ request.path }}{% endif %}" enctype="multipart/form-data" {% if ictarget %}ic-target="{{ ictarget }}"{% endif %} {% if icinclude %}ic-include="{{ icinclude }}{{ icinclude_uuid }}"{% endif %}>
        {% csrf_token %}
        {% if with_next_url %}
            <input type="hidden" name="nexturl" value="{{ next_url }}" />
        {% endif %}
        <div class="row smallskip">
            <div class="col-md-12">
                {% if heading %}<h1>{{ heading }}</h1>{% endif %}

                {%  if sub_form %}
                    {% crispy sub_form %}
                {% endif %}
                {%  if sub_form2 %}
                    {% crispy sub_form2 %}
                {% endif %}
                {% if categories_all %}
                </div>
                <div class="col-md-12">
                    {% include "core/_main_category_select.html" with categories_all=categories_all ds=ds %}
                </div>
                    {% comment %} {% if ds.uuid %}
                    <div class="col-md-4" id="dataset-image" ic-get-from="{% url 'dddatasets:prep_dataset_edit_image' ds.uuid %}" ic-trigger-on="load">
                        <span>
                            <span class="spinner-sm"></span>{% trans "Loading Dataset Image" %}
                        </span>
                    </div>
                    {% endif %} {% endcomment %}
                </div>
                {% endif %}

                <div id='messages2' ic-src="{% url 'core:messages' %}">
                    {% include 'core/_messages.html' %}
                </div>

                {% crispy form %}

                {% if form_err %}
                <p>{{ form_err }}</p>
                {% endif %}

            </div>
        </div>
    </form>
{% endif %}

{% endblock %}

discuss_data/templates/core/_main_category_select.html
{% load static i18n core_tags %}

<div>
    <label>{% trans 'Main Category' %}*</label>
    <div class="btn-group-toggle smallskip" id="main-category-select" data-toggle="buttons">
        {% if ds %}
            {# Edit dataset #}
            {% for category in categories_all %}
                {# checked default is ds.get_main_category#}
                {% if category.id == ds.get_main_category.id %}
                    <label class="btn btn-pill btn-outline-primary badge-tag active">
                        <input type="radio" name="main_category" id="category-{{ category.slug }}" value="{{ category.slug }}" autocomplete="off" checked>
                        {{ category }}
                    </label>
                {% else %}
                    <label class="btn btn-pill btn-outline-primary badge-tag">
                        <input type="radio" name="main_category" id="category-{{ category.slug }}" value="{{ category.slug }}" autocomplete="off">
                        {{ category }}
                    </label>
                {% endif %}
            {% endfor %}
        {% else %}
            {# Add dataset #}
            {% for category in categories_all %}
                {# checked default category other listed as last element #}
                <label class="btn btn-pill btn-outline-primary badge-tag">
                    <input type="radio" name="main_category" id="category-{{ category.slug }}" value="{{ category.slug }}" autocomplete="off" {% if category.slug == "other" %}checked{% endif %}>
                    {{ category }}
                </label>
            {% endfor %}
        {% endif %}
    </div>
    {% if ds %}
        {# Additional Categories only for Edit dataset #}
        <label>{% trans 'Additional Categories' %}</label>
        {% include 'core/_multi_select.html' with fields=ds.get_categories.all fields_all=categories_all selecttype="categories" selecttitle=None %}
    {% endif %}
</div>

discuss_data/templates/core/_manpage_text.html
{% load wagtailcore_tags core_tags i18n %}

{% get_manpage manpage as page %}
{% for block in page.body %}
    {{ block }}
{% endfor %}

discuss_data/templates/core/_messages.html
{% load i18n %}



<div id={{ cssid }} class="position-fixed w-50 text-center">
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class='alert alert-success alert-dismissible fade show' ic-trigger-on='timeout:10s' ic-action='delay:4500;fadeOut;remove' role='alert'>
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class='alert alert-danger alert-dismissible fade show' role='alert'>
                {{ message }}
                {% if err %}
                    {{ target|title }} {% trans 'could not be saved. Error encountered in fields' %} {% for field in err %} {{ field }}, {% endfor %}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
        {% else %}
            <div class='alert alert-warning alert-dismissible fade show' ic-trigger-on='timeout:10s' ic-action='delay:4500;fadeOut;remove' role='alert'>
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
</div>

discuss_data/templates/core/_multi_select.html
{% load static i18n core_tags %}

<div>
    <button class="list-group-item smallskip select-header" type="button" data-toggle="collapse" data-target="#collapse-{{ selecttype }}-field" aria-expanded="{% if fields %}false{% else %}true{% endif %}" aria-controls="collapse-{{ selecttype }}-field">
        {% if selecttitle %}{% trans selecttitle %}: {% endif %} {% if fields %}{% for field in fields %}{{ field|title }}{% if not forloop.last %}, {% endif %}{% endfor %}{% else %}–{% endif %} <span class="select-filter-caret"><span class="i-drop-down-arrow-md"></span></span>
    </button>
</div>
<div class="collapse" id="collapse-{{ selecttype }}-field">
    <div class="list-group smallskip">
        {% for field in fields_all %}
            <input type="checkbox" name="{{ selecttype }}" value="{{ field.id }}" aria-label="{% trans field.name %}"{% if field in fields %} checked{% endif %} id="search-field-{{ field.slug }}" />
            <label class="list-group-item select-field" for="search-field-{{ field.slug }}">{{ field.name }}</label>
        {% endfor %}
    </div>
</div>

discuss_data/templates/core/_search_index.html
{% load static i18n core_tags %}



<div class="list-group">
    <button class="list-group-item active search-filter-button" type="button" data-toggle="collapse" data-target="#collapse-{{ filtertype }}-filter" aria-expanded="false" aria-controls="collapse-{{ filtertype }}-filter">
        {% trans "Search for" %}: {% if filter_applied == 'dataset_index' %}{% trans 'Datasets' %}{% elif filter_applied == 'user_index' %}{% trans 'Users' %}{% else %}{% trans 'Help' %}{% endif %} <span class="search-filter-caret"><span class="i-drop-down-arrow-md"></span></span>
    </button>
</div>
<div class="collapse show" id="collapse-{{ filtertype }}-filter">
    <div class="list-group search-filter smallskip">
        {# dataset_index #}
        <input type="radio" value="dataset_index" aria-label="{% trans 'Datasets' %}" {% if filter_applied == 'dataset_index' %} checked{% else %}ic-get-from="{% url 'dddatasets:search' %}{{ search_params|add_url_search_params }}" ic-push-url="true" ic-include=".search-middle" ic-target="#content"{% endif %} id="search-filter-dataset_index" />
        <label class="list-group-item" for="search-filter-dataset_index">{% trans 'Datasets' %}</label>

        {# user_index #}
        <input type="radio" value="user_index" aria-label="{% trans 'Users' %}" {% if filter_applied == 'user_index' %} checked{% else %}ic-get-from="{% url 'ddusers:search' %}{{ search_params|add_url_search_params }}" ic-push-url="true" ic-include=".search-middle" ic-target="#content"{% endif %} id="search-filter-user_index" />
        <label class="list-group-item" for="search-filter-user_index">{% trans 'Users' %}</label>

        {# help_index #}
        <input type="radio" value="help_index" aria-label="{% trans 'Help' %}" {% if filter_applied == 'help_index' %} checked{% else %}ic-get-from="{% url 'core:help_search' %}" ic-push-url="true" ic-include=".search-middle" ic-target="#content"{% endif %} id="search-filter-help_index" />
        <label class="list-group-item" for="search-filter-help_index">{% trans 'Help' %}</label>
    </div>
</div>