config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail import urls as wagtail_urls

from allauth.account.views import confirm_email

from discuss_data.core.views import (
    landing_page,
    about_page,
    contacts_page,
    security_page,
    login_page,
)
from discuss_data.ddusers.views import datasets_act_feed
from discuss_data.dddatasets.views.core import category_page, category_list
from discuss_data.api.root import api

urlpatterns = [
    # remove next 4 lines and template files!
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #    "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL + "doc/", include("django.contrib.admindocs.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/", include(("discuss_data.ddusers.urls", "ddusers"), namespace="ddusers")
    ),
    # Your stuff: custom urls includes go here
    path("core/", include(("discuss_data.core.urls", "core"), namespace="core")),
    # hitcount
    path("hitcount/", include('hitcount.urls', namespace='hitcount')),
    # path(
    #    "publication/",
    #    include(
    #        ("discuss_data.ddpublications.urls", "ddpublications"),
    #        namespace="ddpublications",
    #    ),
    # ),
    path("dataset/", include("discuss_data.dddatasets.urls", namespace="dddatasets")),
    path("dhrep/", include("discuss_data.dhrep.urls", namespace="dhrep")),
    path('accounts/', include('allauth.urls')),
    # custom account confirmation email url, needs to come below accounts
    path('verify-email/<str:key>/',
        confirm_email,
        name="account_confirm_email"
    ),
    path("", landing_page, name="core.landing_page"),
    path("about/", about_page, name="core.about_page"),
    path("contacts/", contacts_page, name="core.contacts_page"),
    path("security/", security_page, name="core.security_page"),
    path("login/", login_page, name="core.login_page"),
    path("dashboard/", datasets_act_feed, name="ddusers.dashboard_page"),
    path("categories/", category_list, name="category_list"),
    path("categories/<slug:slug>/", category_page, name="category_page"),
    # API
    path("api/", api.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# wagtail URL def
urlpatterns += [
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("documentation/", include(wagtail_urls)),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

discuss_data/core/urls.py
from django.urls import path

from discuss_data.core import views

app_name = "core"

# public URLs
urlpatterns = [
    path("tags/keywords/", views.get_keyword_tags, name="tags"),
    path("polling/start/", views.polling_start, name="polling_start"),
    path("polling/stop/", views.polling_stop, name="polling_stop"),
    path("load/", views.load, name="load"),
    path("messages/", views.messages, name="messages"),
    path("search/", views.help_search, name="help_search"),
]

discuss_data/ddusers/urls.py
from django.urls import path

from discuss_data.ddusers import views


app_name = "ddusers"


urlpatterns = [
    # public URLs
    # path("search/", views.UsersListView.as_view(), name="search"), # this line breaks user search
    path("search/", views.search, name="search"),  # use this for searching
    path("verification/", views.verification_info, name="verification_info"),
    path("terms-of-use/", views.accept_tou, name="accept_tou"),
    path("first-steps/", views.first_steps, name="first_steps"),
    path("<uuid:us_uuid>/", views.UserDetailsView.as_view(), name="detail"),
    path("follow/<uuid:us_uuid>/", views.user_follow, name="follow"),
    path(
        "follow/datalist/<uuid:dl_uuid>/", views.datalist_follow, name="datalist_follow"
    ),
    path("follow/", views.user_follow_status, name="follow_status"),
    path("feed/users/", views.user_act_feed, name="user_feed"),
    path("feed/following/", views.following_act_feed, name="following_feed"),
    path("following/", views.following_users, name="following_users"),
    path("followers/", views.followers_users, name="followers_users"),
    path(
        "following/datasets/",
        views.list_following_datasets,
        name="list_following_datasets",
    ),
    path(
        "following/datalists/",
        views.list_following_datalists,
        name="list_following_datalists",
    ),
    path("followed/<str:follow_type>/", views.list_followed, name="list_followed"),
    # path("feed/notifications", views.notification_act_feed, name="notification_feed"),
    # path("follow/otherfeed/", views.other_feed, name="other_feed"),
    path("<uuid:us_uuid>/affiliations/", views.user_affiliations, name="affiliations",),
    path("<uuid:us_uuid>/datalists/", views.user_data_lists, name="data_lists",),
    path(
        "<uuid:us_uuid>/datalists/<uuid:dl_uuid>",
        views.user_get_data_list,
        name="get_data_list",
    ),
    path("<uuid:us_uuid>/projects/", views.user_projects, name="projects"),
    path("<uuid:us_uuid>/publications/", views.user_publications, name="publications",),
    path("<uuid:us_uuid>/datasets/", views.user_datasets, name="datasets"),
    path("<uuid:us_uuid>/lists/", views.user_lists_public, name="lists_public",),
    path("notifications/", views.user_notifications, name="notifications"),
    path("notifications/add/", views.user_notification, name="notification"),
    # edit urls
    # users search for dataset access control
    path("edit/search/", views.user_search, name="user_search"),
    # user profile: edit pages
    path("edit/", views.user_edit, name="edit"),
    path("edit/profile/", views.user_edit_profile, name="profile_edit"),
    # user profile: data lists
    path("follow/lists/add/dataset", views.dataset_to_list, name="dataset_to_list",),
    path("edit/lists/", views.user_edit_lists, name="edit_lists",),
    path("edit/lists/add/", views.user_edit_data_list, name="edit_list"),
    path("edit/lists/<uuid:dl_uuid>", views.user_edit_data_list, name="edit_list",),
    # user profile: affiliations
    path("edit/affiliations/", views.user_edit_affiliations, name="edit_affiliations",),
    path(
        "edit/affiliations/add/", views.user_edit_affiliation, name="edit_affiliation"
    ),
    path(
        "edit/affiliations/<uuid:af_uuid>/",
        views.user_edit_affiliation,
        name="edit_affiliation",
    ),
    # user profile: projects
    path("edit/projects/", views.user_edit_projects, name="edit_projects"),
    path("edit/projects/add/", views.user_edit_project, name="edit_project"),
    path("edit/projects/<uuid:pr_uuid>/", views.user_edit_project, name="edit_project"),
    # user profile: publications
    path("edit/publications/", views.user_edit_publications, name="edit_publications",),
    path(
        "edit/publications/add/", views.user_edit_publication, name="edit_publication"
    ),
    path(
        "edit/publications/<uuid:pub_uuid>/",
        views.user_edit_publication,
        name="edit_publication",
    ),
    # TODO: integrate ddpublications
    path("edit/countries/", views.user_countries, name="countries"),
    path("edit/tags/", views.user_tags, name="tags"),
    path("curation/", views.user_curation, name="curation"),
]

discuss_data/dhrep/urls.py
from django.urls import path

from discuss_data.dhrep import views

app_name = "dhrep"
urlpatterns = [
    path("token/<token>", views.show_token, name="show_token"),
    path("token/", views.get_token, name="get_token"),
]

discuss_data/dddatasets/views/core.py
import logging

from actstream import actions
from actstream.models import followers
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _
from django_sendfile import sendfile
from django.views.generic.detail import DetailView, View
from hitcount.views import HitCountDetailView, HitCountMixin
from hitcount.models import HitCount

from guardian.shortcuts import get_perms

from discuss_data.core.decorators import dd_tou_accepted, dd_user_verified
from discuss_data.core.helpers import check_perms, is_curator_or_check_perms_for_ds
from discuss_data.core.views import core_search_view, get_search_params
from discuss_data.dddatasets.models import (
    Category,
    DataFile,
    DataSet,
    DataSetAccessRequest,
    DataSetManagementObject,
)
from discuss_data.dddatasets.utils import check_published

logger = logging.getLogger(__name__)


# ************
# public views
# ************


def search(request):
    return core_search_view(request, "dataset_index", 10)


# unused?
def listing(request):
    dsmos = DataSetManagementObject.objects.select_related("main_published_ds")
    datasets = list()
    for dsmo in dsmos:
        if dsmo.main_published_ds:
            datasets.append(dsmo.main_published_ds)

    return render(
        request,
        "dddatasets/listing.html",
        {"datasets": datasets, "pagetitle": _("Datasets")},
    )


def category_list(request):
    categories = Category.objects.all()
    return render(
        request,
        "dddatasets/category_list.html",
        {"categories": categories, "pagetitle": _("Categories")},
    )


def category_page(request, slug):
    logger.debug("category slug: {}".format(slug))
    category = get_object_or_404(Category, slug=slug)
    template = "dddatasets/search_results.html"
    datasets = category.get_published_datasets_category_all()
    search_params = get_search_params(request, None, category)
    # return core_search_view(request, "dataset_index", 10, category=category)
    return render(
        request,
        template,
        {
            "object_list": datasets,
            "search_params": search_params,
            "query": search_params["q"],
            "category": category,
        },
    )

class DataSetPublicHitCountView(HitCountDetailView):
    model = DataSet
    count_hit = True

    def get_object(self, **kwargs):
        return check_published(self.kwargs['uuid'])


class DataSetDetailView(DataSetPublicHitCountView):
    template_name = "dddatasets/detail.html"


class DataSetMetadataView(DataSetPublicHitCountView):
    template_name = "dddatasets/metadata.html"


class DataSetPublicationsView(DataSetPublicHitCountView):
    template_name = "dddatasets/publications.html"


class DataSetDiscussView(DataSetPublicHitCountView):
    template_name = "dddatasets/discuss.html"


class DataSetVersionsView(DataSetPublicHitCountView):
    template_name = "dddatasets/versions.html"


class DataSetFilesView(DataSetPublicHitCountView):
    template_name = "dddatasets/files.html"

    def get_datafiles(self, **kwargs):
        logger.debug("get datafiles")
        datafiles = list()
        ds = self.get_object(**kwargs)
        for datafile in ds.get_datafiles():
            try:
                filesize = datafile.file.size
            except FileNotFoundError:
                filesize = 10
            if datafile.data_file_type in (
                datafile.FILE_TYPE_DATA,
                datafile.FILE_TYPE_CONVERTED,
            ):
                # if dataset is RA check permissions
                if (
                    ds.data_access != ds.RESTRICTED_ACCESS
                    or is_curator_or_check_perms_for_ds(
                        "ra_view_dataset", self.request.user, datafile.dataset
                    )
                ):
                    datafiles.append(
                        (datafile, filesize, datafile.get_file_format(), datafile.hit_count.hits)
                    )
                else:
                    datafiles.append(("RA", filesize, datafile.get_file_format(), datafile.hit_count.hits))
            else:
                logger.debug(f"append {datafile}, type {type(datafile)}")
                datafiles.append((datafile, filesize, datafile.get_file_format(), datafile.hit_count.hits))
        return datafiles

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["datafiles"] = self.get_datafiles(**kwargs)
        return context


def files_pdf(request, uuid):
    ds = get_object_or_404(DataSet, uuid=uuid)
    try:
        pdf_file = DataFile.objects.filter(dataset=ds, data_file_type="PDF")[0]
    except DataFile.DoesNotExist as e:
        raise Http404 from e
    return download(request, pdf_file)


def files_zip(request, uuid):
    ds = get_object_or_404(DataSet, uuid=uuid)
    datafile = get_object_or_404(DataFile, dataset=ds, data_file_type="ZIP")

    if ds.data_access != ds.RESTRICTED_ACCESS or is_curator_or_check_perms_for_ds(
        "ra_view_dataset", request.user, datafile.dataset
    ):
        return download(request, datafile)
    return HttpResponseForbidden()


def files_download(request, uuid, df_uuid):
    logger.debug(f"File download")
    ds = get_object_or_404(DataSet, uuid=uuid)
    datafile = get_object_or_404(DataFile, uuid=df_uuid, dataset=ds)
    logger.info("datafile.file.path: %s", datafile.file.path, exc_info=1)
    logger.info(
        "datafile.get_download_file_name(): %s", datafile.get_download_file_name()
    )
    # check permissions for the dataset if it is of filetype DATA or CONVERTED
    if datafile.data_file_type in (
        datafile.FILE_TYPE_DATA,
        datafile.FILE_TYPE_CONVERTED,
    ):
        # if dataset is RA check permissions
        if (
            ds.data_access != ds.RESTRICTED_ACCESS
            or is_curator_or_check_perms_for_ds(
                "ra_view_dataset", request.user, datafile.dataset
            )
            or "view_dsmo"
            or "admin_dsmo"
            or "edit_dsmo" in get_perms(request.user, ds.dataset_management_object)
        ):
            return download(request, datafile)
        logger.debug(f"File download forbidden: {datafile}")
        return HttpResponseForbidden()
    return download(request, datafile)


def download(request, datafile):
    """sendfile download wrapper"""
    # count hit
    hit_count = HitCount.objects.get_for_object(datafile)
    hit_count_response = HitCountMixin.hit_count(request, hit_count)
    logger.debug(f"File download: {datafile}, {hit_count_response}")

    return sendfile(
        request,
        datafile.file.path,
        attachment=True,
        attachment_filename=datafile.get_download_file_name(),
    )








# ************
# views that require log-in
# ************
@login_required
@dd_tou_accepted
@dd_user_verified
def follow(request, uuid):
    # redirect if no intercooler request
    if not request.is_intercooler():
        return redirect("dddatasets:search")
    dataset = get_object_or_404(DataSet, uuid=uuid)

    if request.user in followers(dataset):
        actions.unfollow(request.user, dataset)
    else:
        actions.follow(request.user, dataset)
    return render(
        request,
        "ddusers/_follow_button.html",
        {
            "object": dataset,
            "follow_url": "dddatasets:follow",
            "follow_text": "Follow this Dataset",
        },
    )


@login_required
@dd_tou_accepted
@dd_user_verified
def access_request(request, uuid):
    ds = check_published(uuid)
    # check restricted access view permissions for the dataset
    if check_perms("ra_view_dataset", request.user, ds):
        # user has already access
        return HttpResponse(
            '<button class="btn btn-success" disabled>{}</button>'.format(
                _("You have access to this Dataset")
            )
        )

    if request.method == "POST":
        ds_access_request = DataSetAccessRequest(dataset=ds, user=request.user)
        ds_access_request.save()

        return HttpResponse(
            '<button class="btn btn-secondary" disabled>{}</button>'.format(
                ds_access_request
            )
        )
    else:
        ds_access_request = ds.get_access_request(request.user)
        if ds_access_request:
            return HttpResponse(
                '<button class="btn btn-secondary" disabled>{}</button>'.format(
                    ds_access_request
                )
            )
    return render(
        request,
        "dddatasets/_access_request.html",
        {
            "add_url": "dddatasets:access_request",
            "object": ds,
            "btn_text": "Request Access",
        },
    )

discuss_data/docupages/views.py
# Create your views here.

discuss_data/templates/ddusers/_base_profile.html
{% extends request.is_intercooler|yesno:"blank.html,base.html" %}

{% load static i18n %}


{% block title %}
Edit {{ user.username }}'s Profile
{% endblock %}



{% block content %}
<div class="row">
    <div class="col-md-12">
    {% block ic-content %}
    {% endblock ic-content %}
    </div>
</div>

{% endblock content %}

discuss_data/templates/ddusers/_datalist_button.html
{% load static i18n %}

{% if btn_mode == "add" %}
    <div>
        <button class="btn btn-danger smallskip" ic-delete-from="{% url 'ddusers:dataset_to_list' %}" ic-target="#ds-{{dataset.uuid}}-to-{{datalist.uuid}}-button" ic-on-beforeSend="xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');">{% trans 'Remove from' %} {{ datalist }} ({{ datalist.get_status }})</button>
    </div>
{% else %}
    <div>
        <button class="btn btn-outline-primary smallskip" ic-post-to="{% url 'ddusers:dataset_to_list' %}" ic-target="#ds-{{dataset.uuid}}-to-{{datalist.uuid}}-button">{% trans "Add to" %} {{ datalist }} ({{ datalist.get_status }})</button>
    </div>
{% endif %}

discuss_data/templates/ddusers/_feed.html
{% load static i18n activity_tags core_tags %}

{% for action in feed_actions %}
    {% if feed_type == "notifications" or feed_type == "curation" %}
        {% include 'ddcomments/_notification_card.html' with comment=action form=form %}
    {% else %}
        {% include 'ddusers/_feed_card.html' with action=action feed_type=feed_type %}
    {% endif %}
{% endfor %}

{% include 'core/_pagination.html' with object_list=feed_actions paginator_range=paginator_range paginator_last_page=paginator_last_page ic_target='#dashboard' %}

discuss_data/templates/ddusers/_followed_datasets_header.html
{% load static i18n %}

<h1>{% trans title %}</h1>
<div class="row">
    <div class="col-xs-7">
        <ul class="nav nav-pills navbar-right nav-datasets" ic-target="#ds-content" ic-push-url="true">
            <li class="{% if object_type == "datasets_followed" %}nav-active{% endif %}">
                <button class="btn btn-link" ic-get-from="{% url 'ddusers:list_following_datasets' %}">{% trans "Followed Datasets" %}</button>
            </li>
            <li class="{% if object_type == "datalists_followed" %}nav-active{% endif %}">
                <button class="btn btn-link" ic-get-from="{% url 'ddusers:list_following_datalists' %}">{% trans "Followed Data Lists" %}</button>
            </li>
        </ul>
    </div>
</div>

discuss_data/templates/ddusers/_search_results.html
{% extends request.is_intercooler|yesno:"blank.html,base.html" %}
{% load static i18n core_tags %}

{% block content %}
{% block ic-content %}
{% if search_type == 'pubaccess_search' or search_type == 'collaboration_search' or search_type == 'ownership_search' %}
  {# search object list for embedded user search w/o filters, big search field, pagination #}
  {% if object_list %}
    {% for object in object_list %}
        {% if search_type %}
          {% include 'ddusers/_user_detail_card.html' with object=object image_url=objectimage.url dsid=ds.uuid cardtype=search_type ds=ds %}
        {% else %}
          {% include 'ddusers/_user_detail_card.html' with object=object image_url=objectimage.url %}
        {% endif %}
    {% endfor %}

  {% else %}
    {% trans "Nothing found" %}
  {% endif %}

{% else %}
  <div id="search-list">
    <div class="row">
      <div class="col-md-9">
        <h2>{% trans "People on Discuss Data" %}</h2>
        {# big search field #}
        <div class="input-group mb-3 search-field-main">
          <input class="form-control search-field-main search-middle search-data search-ui"{% if query %}value="{{ query }}"{% else %}placeholder="Search"{% endif %} name="q" aria-label="Search">
          <div class="input-group-append">
            <button class="input-group-text search-button" type="button" ic-include=".search-data" ic-get-from="{% url 'ddusers:search' %}" ic-target="#content" ic-push-url="true" ic-push-params="q,countries,keywords"><span class="i-search-md"></span></button>
          </div>
        </div>

        {# search object list #}
        {% if object_list %}

        <p>{% if object_list.paginator %}{{ object_list.paginator.count }}{% else %}{{ object_list.count }}{% endif %} {% trans "Discuss Data Users found" %}</p>
          {% for object in object_list %}
              {% if search_type %}
                {% include 'ddusers/_user_detail_card.html' with object=object image_url=objectimage.url dsid=ds.uuid cardtype=search_type %}
              {% else %}
                {% include 'ddusers/_user_detail_card.html' with object=object image_url=objectimage.url %}
              {% endif %}
          {% endfor %}

          {# pagination #}
          {% if pagination %}
            {% include 'core/_pagination.html' with object_list=object_list paginator_range=paginator_range paginator_last_page=paginator_last_page ic_target='#search-list' %}
          {% endif %}

        {% else %}
          {% trans "Nothing found" %}
        {% endif %}
      </div>

      {# filters #}
      <div class="col-md-3">
        {% include 'dddatasets/search_filters_partial.html' with search_index=search_index search_index_all=search_index_all filter_applied="user_index" search_params=search_params %}
      </div>
    </div>
  </div>
{% endif %}

{% endblock ic-content %}
{% endblock content %}

discuss_data/templates/ddusers/_user_main_affiliation.html
{% for affiliation in object.get_main_affiliation %}
    {{ affiliation.position }}, {{ affiliation.name_of_institution }}, {{ affiliation.place_of_institution }} ({{ affiliation.country_of_institution }})
    {% if not forloop.last %} / {% endif %}
{% endfor %}

discuss_data/templates/ddusers/_user_search_list.html
{% load static %}


<div class="row" id="user-list">
    <div class="col-md-12">
    {% if users %}
        {% for object in users %}
            <hr>
            <div class="media">
                <div class='media-left'>
                {% if object.photo %}
                    <a href="{# {% url 'user_detail' object.uuid %} #}"><img src="{{ object.photo.url }}" height="60" class="media-object img-circle" /></a>
                {% endif %}
                </div>
                <div class='media-body'>
                    <p class="media-heading"><a href="{# {% url 'user_detail' object.uuid %} #}">{{object.get_academic_name}}</a>
                    {% for affiliation in object.get_main_affiliation %}
                        {% if affiliation.main %}
                        <p>{{ affiliation.position }}, {{ affiliation.name_of_institution }}, {{ affiliation.place_of_institution }} ({{ affiliation.country_of_institution }})</p>
                        {% endif %}
                    {% endfor %}
                    <div id="ds-add-user-{{ object.uuid}}">
                    <form>
                    {% csrf_token %}
                    <input type="hidden" value="{{ object.uuid }}" name="userid">

                    <button type="button" class="btn{% if tag.1 %} btn-success{% else %} btn-default{% endif %}"
                    ic-post-to="{% url 'dddatasets:prep_edit_access_user_add' oep.dsid groupid  %}" ic-target="#ds-content">Add to {{ objecttype }}</button>
                    </form>
                    </div>
                    </p>
                </div>
                <span class="spinner" id="indicator-paginator"></span>

            </div>
        {% endfor %}
    {% else %}
        <div class="col-md-6">No users found with query {{ query }}.</div>
    {% endif %}
    </div>
</div>

discuss_data/templates/ddusers/_user_sidebar_image.html
{% load static i18n compress%}

<div class="img-container container">
    <div id="image-circle">
        {% if user.photo %}
            <img id="image" src="{{ user.photo.url }}" class="avatar media-object" />
        {% else %}
            <img src={% static "images/user_default.svg" %} class="avatar media-object" />
        {% endif %}
        {% if editmode %}
            <div id="image-overlay" data-toggle="modal" data-target="#userImageModal" ic-target="#confirmModal-target-span">
                <span class="i-camera-md"></span>
            </div>
        {% endif %}
    </div>
</div>

discuss_data/templates/ddusers/change_password.html
{% load static %}

{% block content %}
{% if updated %}
    <div id="updated-msg" class="alert alert-success" role="alert">
        <strong>Password changed</strong>
    </div>
{% endif %}
{% if form %}
<form method="post">
  {% csrf_token %}
    <div class="row">
        <div class="col-md-12">
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% for error in field.errors %}
                    <div class="alert alert-warning">{{ error }}</div>
                {% endfor %}
                {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            </div>
        {% endif %}
            {% endfor %}
            <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" >Close</span></button>
            <button type="button" class="btn btn-primary" ic-post-to="{{ request.path }}" ic-target="#userpasswordModal-target-span">Save changed password</button>
            </div>
    </div>
</form>
{% endif %}
{% if error_msg %}
<p>{{ error_msg }}</p>
{% endif %}
{% endblock %}

discuss_data/templates/ddusers/data_lists.html
{% extends request.is_intercooler|yesno:"blank.html,ddusers/_base_profile.html" %}
{% load static i18n %}

{% block title %}{{ user.get_full_name }}{% endblock %}

{% block ic-content %}
<div id="ds-content">
    {% block dataset-nav %}
        {% include 'ddusers/_profile_header.html' with type='data_lists' %}
    {% endblock dataset-nav %}

    {% if manpage %}
        {% include 'dddatasets/_manual_page.html' with manpage=manpage %}
    {% endif %}

    <h3>{% trans "Data Lists" %}</h3>
    {% if user.get_lists_public %}
        {% for data_list in user.get_lists_public %}
            {% include 'dddatasets/_datalist_card.html' with data_list=data_list edit_url=edit_url editmode=False %}
        {% endfor %}
    {% else %}
        <p>{% trans "No public data lists have been created yet" %}</p>
    {% endif %}

</div>
{% endblock ic-content %}

discuss_data/templates/ddusers/datasets.html
{% extends request.is_intercooler|yesno:"blank.html,ddusers/_base_profile.html" %}
{% load static i18n %}

{% block title %}{{ user.get_full_name }}{% endblock %}

{% block ic-content %}
<div id="ds-content">
    {% block dataset-nav %}
        {% include 'ddusers/_profile_header.html' with type='dataset' %}
    {% endblock dataset-nav %}

    {% if manpage %}
        {% include 'dddatasets/_manual_page.html' with manpage=manpage %}
    {% endif %}

    <h3>{% trans "Datasets" %}</h3>
    {% if user.get_published_datasets %}
        {% for dataset in user.get_published_datasets %}
            {% include "dddatasets/_dataset_card.html" with dataset=dataset prep=False userpage=True %}
        {% endfor %}
    {% else %}
        <p>{% trans "No datasets listed" %}</p>
    {% endif %}

</div>
{% endblock ic-content %}

discuss_data/templates/ddusers/projects.html
{% extends request.is_intercooler|yesno:"blank.html,ddusers/_base_profile.html" %}
{% load static i18n %}

{% block title %}{{ user.get_full_name }}{% endblock %}

{% block ic-content %}
<div id="ds-content">
    {% block dataset-nav %}
        {% include 'ddusers/_profile_header.html' with type='project' %}
    {% endblock dataset-nav %}

    {% if manpage %}
        {% include 'dddatasets/_manual_page.html' with manpage=manpage %}
    {% endif %}

    <h3>{% trans "Projects" %}</h3>
    {% if user.get_projects %}
        {% for object in user.get_projects %}
            {% include "ddusers/_project_card.html" with object=object %}
        {% endfor %}
    {% else %}
        <p>{% trans "No projects listed" %}</p>
    {% endif %}
</div>
{% endblock ic-content %}